version: '3'
services:
  go_gin_api_db:
    build: db/go_gin_api_db
    container_name: go_gin_api_db_dev
    ports:
      - 3306:3306
    volumes:
      - mysql-go-gin-sample-app-data:/var/lib/mysql
      - ./db/go_gin_api_db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_APP_USER: sample
      MYSQL_APP_USER_PASSWORD: sample
      MYSQL_DATABASE: sample 
    restart: unless-stopped
volumes:
  mysql-go-gin-sample-app-data:
    driver: local
