version: '3'
services:
  go_gin_api_app:
    build: src
    container_name: go_gin_api_app
    ports:
      - 8080:8080
    environment:
      GOPATH: "/go"
      go_gin_api_DB_USER: root
      go_gin_api_DB_PASS: sample
      go_gin_api_DB_NAME: sample
      go_gin_api_DB_HOSTNAME: go_gin_api_db
      go_gin_api_DB_PORT: 3306
      go_gin_api_LOG_PATH: "/go/src/github.com/inagacky/go_gin_api/log"
    restart: unless-stopped
    networks:
      - go_gin_api_net

  go_gin_api_db:
    build: db/go_gin_api_db
    container_name: go_gin_api_db
    ports:
      - 3306:3306
    volumes:
      - mysql-go-gin-sample-app-data:/var/lib/mysql
      - ./db/go_gin_api_db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_APP_USER: sample
      MYSQL_APP_USER_PASSWORD: sample
      MYSQL_DATABASE: sample 
    restart: unless-stopped
    networks:
      - go_gin_api_net
volumes:
  mysql-go-gin-sample-app-data:
    driver: local

networks:
  go_gin_api_net:
    driver: bridge