version: '3'
services:
  go_gin_sample_app:
    build: src
    container_name: go_gin_sample_app
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - ./src:/go/src/github.com/inagacky/go_gin_sample/src
    security_opt:
      - apparmor:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      GOPATH: "/go"
      GO_GIN_SAMPLE_DB_USER: root
      GO_GIN_SAMPLE_DB_PASS: sample
      GO_GIN_SAMPLE_DB_NAME: sample
      GO_GIN_SAMPLE_DB_HOSTNAME: go_gin_sample_db
      GO_GIN_SAMPLE_DB_PORT: 3306
      GO_GIN_SAMPLE_LOG_PATH: "/log"
    restart: unless-stopped
    networks:
      - go_gin_sample_net

  go_gin_sample_db:
    build: db/go_gin_sample_db
    container_name: go_gin_sample_db
    ports:
      - 3306:3306
    volumes:
      - mysql-go-gin-sample-app-data:/var/lib/mysql
      - ./db/go_gin_sample_db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_APP_USER: sample
      MYSQL_APP_USER_PASSWORD: sample
      MYSQL_DATABASE: sample 
    restart: unless-stopped
    networks:
      - go_gin_sample_net
volumes:
  mysql-go-gin-sample-app-data:
    driver: local

networks:
  go_gin_sample_net:
    driver: bridge