version: '3'
services:
  go_graphql_app_db:
    build: ./db/go_graphql_app_db 
    container_name: go_graphql_app_db
    ports:
      - 33006:3306
    volumes:
      - mysql-go-graphql-app-data:/var/lib/mysql
      - ./db/go_graphql_app_db/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: sample
      MYSQL_APP_USER: sample
      MYSQL_APP_USER_PASSWORD: sample
      MYSQL_DATABASE: sample 
    restart: unless-stopped
volumes:
  mysql-go-graphql-app-data:
    driver: local
